# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 101, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 511, 471))
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 60, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 150, 101, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 210, 91, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(660, 60, 80, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(660, 150, 80, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(660, 210, 80, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(560, 260, 91, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(660, 260, 80, 23))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 310, 91, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(660, 310, 80, 23))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(610, 360, 91, 20))
        self.label_9.setObjectName("label_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(560, 100, 171, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(560, 390, 181, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_4.setChecked(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(560, 20, 91, 16))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(560, 450, 181, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(600, 420, 91, 20))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menu_n_lem = QtWidgets.QMenu(self.menubar)
        self.menu_n_lem.setObjectName("menu_n_lem")
        self.menuFiltre = QtWidgets.QMenu(self.menubar)
        self.menuFiltre.setObjectName("menuFiltre")
        self.menuMorfolojik = QtWidgets.QMenu(self.menubar)
        self.menuMorfolojik.setObjectName("menuMorfolojik")
        self.menuSegmentasyon = QtWidgets.QMenu(self.menubar)
        self.menuSegmentasyon.setObjectName("menuSegmentasyon")
        self.menuMelih = QtWidgets.QMenu(self.menubar)
        self.menuMelih.setObjectName("menuMelih")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGenisletme = QtWidgets.QAction(MainWindow)
        self.actionGenisletme.setObjectName("actionGenisletme")
        self.actionAsindirma = QtWidgets.QAction(MainWindow)
        self.actionAsindirma.setObjectName("actionAsindirma")
        self.actionAcma = QtWidgets.QAction(MainWindow)
        self.actionAcma.setObjectName("actionAcma")
        self.actionKapama = QtWidgets.QAction(MainWindow)
        self.actionKapama.setObjectName("actionKapama")
        self.actionOtsu_Esikleme = QtWidgets.QAction(MainWindow)
        self.actionOtsu_Esikleme.setObjectName("actionOtsu_Esikleme")
        self.actionDortlu_Komsuluk = QtWidgets.QAction(MainWindow)
        self.actionDortlu_Komsuluk.setObjectName("actionDortlu_Komsuluk")
        self.actionK_Means_Gri = QtWidgets.QAction(MainWindow)
        self.actionK_Means_Gri.setObjectName("actionK_Means_Gri")
        self.actionK_Means_Renkli = QtWidgets.QAction(MainWindow)
        self.actionK_Means_Renkli.setObjectName("actionK_Means_Renkli")
        self.actionBulaniklastirma = QtWidgets.QAction(MainWindow)
        self.actionBulaniklastirma.setObjectName("actionBulaniklastirma")
        self.actionKeskinlestirme = QtWidgets.QAction(MainWindow)
        self.actionKeskinlestirme.setObjectName("actionKeskinlestirme")
        self.actionOrtanca_Filtresi = QtWidgets.QAction(MainWindow)
        self.actionOrtanca_Filtresi.setObjectName("actionOrtanca_Filtresi")
        self.actionLaplace_Filtresi = QtWidgets.QAction(MainWindow)
        self.actionLaplace_Filtresi.setObjectName("actionLaplace_Filtresi")
        self.actionPrewitt_Kenar_Bulma = QtWidgets.QAction(MainWindow)
        self.actionPrewitt_Kenar_Bulma.setObjectName("actionPrewitt_Kenar_Bulma")
        self.actionGriye_Cevir = QtWidgets.QAction(MainWindow)
        self.actionGriye_Cevir.setObjectName("actionGriye_Cevir")
        self.actionBuyuKucul = QtWidgets.QAction(MainWindow)
        self.actionBuyuKucul.setObjectName("actionBuyuKucul")
        self.actionResim_Ac = QtWidgets.QAction(MainWindow)
        self.actionResim_Ac.setObjectName("actionResim_Ac")
        self.actionKaydet = QtWidgets.QAction(MainWindow)
        self.actionKaydet.setObjectName("actionKaydet")
        self.actionYeniden_Boyutlandir = QtWidgets.QAction(MainWindow)
        self.actionYeniden_Boyutlandir.setObjectName("actionYeniden_Boyutlandir")
        self.actionKes = QtWidgets.QAction(MainWindow)
        self.actionKes.setObjectName("actionKes")
        self.actionbas = QtWidgets.QAction(MainWindow)
        self.actionbas.setObjectName("actionbas")
        self.actionsb_cevir = QtWidgets.QAction(MainWindow)
        self.actionsb_cevir.setObjectName("actionsb_cevir")
        self.actionHistogram_Ciz = QtWidgets.QAction(MainWindow)
        self.actionHistogram_Ciz.setObjectName("actionHistogram_Ciz")
        self.actionters_al = QtWidgets.QAction(MainWindow)
        self.actionters_al.setObjectName("actionters_al")
        self.menuDosya.addAction(self.actionResim_Ac)
        self.menuDosya.addSeparator()
        self.menuDosya.addAction(self.actionKaydet)
        self.menuDosya.addSeparator()
        self.menu_n_lem.addAction(self.actionGriye_Cevir)
        self.menu_n_lem.addSeparator()
        self.menu_n_lem.addAction(self.actionBuyuKucul)
        self.menu_n_lem.addSeparator()
        self.menu_n_lem.addAction(self.actionYeniden_Boyutlandir)
        self.menu_n_lem.addSeparator()
        self.menu_n_lem.addAction(self.actionKes)
        self.menu_n_lem.addSeparator()
        self.menu_n_lem.addAction(self.actionHistogram_Ciz)
        self.menuFiltre.addAction(self.actionBulaniklastirma)
        self.menuFiltre.addSeparator()
        self.menuFiltre.addAction(self.actionKeskinlestirme)
        self.menuFiltre.addSeparator()
        self.menuFiltre.addAction(self.actionOrtanca_Filtresi)
        self.menuFiltre.addSeparator()
        self.menuFiltre.addAction(self.actionLaplace_Filtresi)
        self.menuFiltre.addSeparator()
        self.menuFiltre.addAction(self.actionPrewitt_Kenar_Bulma)
        self.menuMorfolojik.addAction(self.actionGenisletme)
        self.menuMorfolojik.addSeparator()
        self.menuMorfolojik.addAction(self.actionAsindirma)
        self.menuMorfolojik.addSeparator()
        self.menuMorfolojik.addAction(self.actionAcma)
        self.menuMorfolojik.addSeparator()
        self.menuMorfolojik.addAction(self.actionKapama)
        self.menuSegmentasyon.addAction(self.actionOtsu_Esikleme)
        self.menuSegmentasyon.addSeparator()
        self.menuSegmentasyon.addAction(self.actionDortlu_Komsuluk)
        self.menuSegmentasyon.addSeparator()
        self.menuSegmentasyon.addAction(self.actionK_Means_Gri)
        self.menuSegmentasyon.addSeparator()
        self.menuSegmentasyon.addAction(self.actionK_Means_Renkli)
        self.menuMelih.addAction(self.actionbas)
        self.menuMelih.addSeparator()
        self.menuMelih.addAction(self.actionsb_cevir)
        self.menuMelih.addSeparator()
        self.menuMelih.addAction(self.actionters_al)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menu_n_lem.menuAction())
        self.menubar.addAction(self.menuFiltre.menuAction())
        self.menubar.addAction(self.menuMorfolojik.menuAction())
        self.menubar.addAction(self.menuSegmentasyon.menuAction())
        self.menubar.addAction(self.menuMelih.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Yeni Boyut:"))
        self.label_4.setText(_translate("MainWindow", "Filtre Boyutu(nxn):"))
        self.label_5.setText(_translate("MainWindow", "Kes(x1,y1,x2,y2):"))
        self.lineEdit.setText(_translate("MainWindow", "300,300"))
        self.lineEdit_2.setText(_translate("MainWindow", "5"))
        self.lineEdit_3.setText(_translate("MainWindow", "0,0,10,10"))
        self.label_6.setText(_translate("MainWindow", "Goruntu Boyutu"))
        self.label_7.setText(_translate("MainWindow", "Kümeleme icin K:"))
        self.lineEdit_4.setText(_translate("MainWindow", "2"))
        self.label_8.setText(_translate("MainWindow", "Buyult-Kucult(2x)"))
        self.lineEdit_5.setText(_translate("MainWindow", "0.5"))
        self.label_9.setText(_translate("MainWindow", "Kayit Türü:"))
        self.radioButton.setText(_translate("MainWindow", "Padding var"))
        self.radioButton_2.setText(_translate("MainWindow", "Padding Yok"))
        self.radioButton_3.setText(_translate("MainWindow", "jpg"))
        self.radioButton_4.setText(_translate("MainWindow", "png"))
        self.radioButton_5.setText(_translate("MainWindow", "tiff"))
        self.radioButton_7.setText(_translate("MainWindow", "Kare"))
        self.radioButton_6.setText(_translate("MainWindow", "Artı"))
        self.label_11.setText(_translate("MainWindow", "Yapısal eleman:"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.menu_n_lem.setTitle(_translate("MainWindow", "On_Islem"))
        self.menuFiltre.setTitle(_translate("MainWindow", "Filtre"))
        self.menuMorfolojik.setTitle(_translate("MainWindow", "Morfolojik"))
        self.menuSegmentasyon.setTitle(_translate("MainWindow", "Segmentasyon"))
        self.menuMelih.setTitle(_translate("MainWindow", "Melih"))
        self.actionGenisletme.setText(_translate("MainWindow", "Genisletme"))
        self.actionAsindirma.setText(_translate("MainWindow", "Asindirma"))
        self.actionAcma.setText(_translate("MainWindow", "Acma"))
        self.actionKapama.setText(_translate("MainWindow", "Kapama"))
        self.actionOtsu_Esikleme.setText(_translate("MainWindow", "Otsu_Esikleme"))
        self.actionDortlu_Komsuluk.setText(_translate("MainWindow", "Dortlu_Komsuluk"))
        self.actionK_Means_Gri.setText(_translate("MainWindow", "K-Means_Gri"))
        self.actionK_Means_Renkli.setText(_translate("MainWindow", "K-Means_Renkli"))
        self.actionBulaniklastirma.setText(_translate("MainWindow", "Bulaniklastirma"))
        self.actionKeskinlestirme.setText(_translate("MainWindow", "Keskinlestirme"))
        self.actionOrtanca_Filtresi.setText(_translate("MainWindow", "Ortanca_Filtresi"))
        self.actionLaplace_Filtresi.setText(_translate("MainWindow", "Laplace_Filtresi"))
        self.actionPrewitt_Kenar_Bulma.setText(_translate("MainWindow", "Prewitt_Kenar_Bulma"))
        self.actionGriye_Cevir.setText(_translate("MainWindow", "Griye_Cevir"))
        self.actionBuyuKucul.setText(_translate("MainWindow", "Buyultme-Kucultme"))
        self.actionResim_Ac.setText(_translate("MainWindow", "Ac"))
        self.actionKaydet.setText(_translate("MainWindow", "Kaydet"))
        self.actionYeniden_Boyutlandir.setText(_translate("MainWindow", "Yeniden_Boyutlandir"))
        self.actionKes.setText(_translate("MainWindow", "Kes"))
        self.actionbas.setText(_translate("MainWindow", "bas"))
        self.actionsb_cevir.setText(_translate("MainWindow", "sb_cevir"))
        self.actionHistogram_Ciz.setText(_translate("MainWindow", "Histogram_Ciz"))
        self.actionters_al.setText(_translate("MainWindow", "ters_al"))
